=== BackupTheBerlios/deepamehta-svn/trunk/develop/src/de/deepamehta/launchpad/setup/ContentsDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://www.deepamehta.de/schema/ContentsDefinition.xsd"
	xmlns="http://www.deepamehta.de/schema/ContentsDefinition.xsd"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:complexType name="propertyType">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="topicType">
		<xsd:sequence>
			<xsd:element name="property" type="propertyType" minOccurs="0"
				maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required"/>
		<xsd:attribute name="version" type="xsd:integer" default="1"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="typeversion" type="xsd:integer" default="1"/>
	</xsd:complexType>
	
	<xsd:complexType name="associationType">
		<xsd:sequence>
			<xsd:element name="property" type="propertyType" minOccurs="0"
				maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required"/>
		<xsd:attribute name="name" type="xsd:string" default=""/>
		<xsd:attribute name="version" type="xsd:integer" default="1"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="typeversion" type="xsd:integer" default="1"/>
		<xsd:attribute name="from" type="xsd:string" use="required"/>
		<xsd:attribute name="fromversion" type="xsd:integer" default="1"/>
		<xsd:attribute name="to" type="xsd:string" use="required"/>
		<xsd:attribute name="toversion" type="xsd:integer" default="1"/>
	</xsd:complexType>
	
	<xsd:complexType name="topicmapType">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="property" type="propertyType"/>
				<xsd:element name="viewtopic">
					<xsd:complexType>
						<xsd:attribute name="id" type="xsd:string" use="required"/>
						<xsd:attribute name="version" type="xsd:integer" default="1"/>
						<xsd:attribute name="x" type="xsd:integer" use="required"/>
						<xsd:attribute name="y" type="xsd:integer" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="viewassociation">
					<xsd:complexType>
						<xsd:attribute name="id" type="xsd:string" use="required"/>
						<xsd:attribute name="version" type="xsd:integer" default="1"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required"/>
		<xsd:attribute name="version" type="xsd:integer" default="1"/>
		<xsd:attribute name="name" type="xsd:string" default=""/>
	</xsd:complexType>
	
	<xsd:element name="contents">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:choice>
					<xsd:element name="topic" type="topicType"/>
					<xsd:element name="association" type="associationType"/>
					<xsd:element name="topicmap" type="topicmapType"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="modelVersion" type="xsd:integer" use="required"/>
			<xsd:attribute name="contentVersion" type="xsd:integer" use="required"/>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== BackupTheBerlios/deepamehta-svn/trunk/develop/apps/example/data/ExampleContents.xml
<?xml version="1.0" encoding="UTF-8"?>
<dmc:contents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.deepamehta.de/schema/ContentsDefinition.xsd ContentsDefinition.xsd" xmlns:dmc="http://www.deepamehta.de/schema/ContentsDefinition.xsd">
	
	<topic id="tt-ex-counter" name="Counter" type="tt-topictype">
		<property name="Name" value="Counter"/>
		<property name="Plural Name" value="Counters"/>
		<property name="Icon" value="example-counter.gif"/>
	</topic>	

	<topic id="pp-ex-counterval" name="Value" type="tt-property">
		<property name="Name" value="Counter Value"/>
		<property name="Visualization" value="Input Field"/>
	</topic>

	<association id="a-ex-1" type="at-composition" from="tt-ex-counter" to="pp-ex-countervaÃ¶">
		<property name="Ordinal Number" value="150"/>
	</association>
	
</dmc:contents>
